### ISSUE TITLE
remove need for www

### ISSUE THREAD

**Issue by gbinal** [benbalter/is-pennsylvania-avenue-closed#10]
I think I just took care of this by creating a cname for * in addition to the one for www.

**Comment by benbalter** [comment]
@gbinal it looks like there's no A record set for the root domain (ironically, the same problem many .govs have). See https://devcenter.heroku.com/articles/custom-domains#root-domain and https://devcenter.heroku.com/articles/apex-domains. If need be, we can move the DNS to my DNSSimple account, which supports ALIAS domains.

**Comment by benbalter** [comment]
Fixed.
